// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXuqpRlFkKPhDvd3vlhEZFxwPtr4aUXk',
    appId: '1:481443766640:web:ccb6e177fe495ac8a32fb5',
    messagingSenderId: '481443766640',
    projectId: 'b6spotify6477',
    authDomain: 'b6spotify6477.firebaseapp.com',
    storageBucket: 'b6spotify6477.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAItzZwTH9KrnbzF8RvW3A3pzQUVQVKung',
    appId: '1:481443766640:android:5b969e434f71c9d1a32fb5',
    messagingSenderId: '481443766640',
    projectId: 'b6spotify6477',
    storageBucket: 'b6spotify6477.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgticp18YQHRGuN5jcbdx4BkFNY5JvhP8',
    appId: '1:481443766640:ios:243e75de2ba55624a32fb5',
    messagingSenderId: '481443766640',
    projectId: 'b6spotify6477',
    storageBucket: 'b6spotify6477.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgticp18YQHRGuN5jcbdx4BkFNY5JvhP8',
    appId: '1:481443766640:ios:243e75de2ba55624a32fb5',
    messagingSenderId: '481443766640',
    projectId: 'b6spotify6477',
    storageBucket: 'b6spotify6477.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzXuqpRlFkKPhDvd3vlhEZFxwPtr4aUXk',
    appId: '1:481443766640:web:89ba43a2fbc3b543a32fb5',
    messagingSenderId: '481443766640',
    projectId: 'b6spotify6477',
    authDomain: 'b6spotify6477.firebaseapp.com',
    storageBucket: 'b6spotify6477.appspot.com',
  );
}
